require("fzf-lua").setup({
  files ={cwd_prompt=false}
})

-- Files
vim.keymap.set("n", "<leader><leader>", function()
	FzfLua.files()
end, { desc = "Files" })
vim.keymap.set("n", "<leader>sf", function()
	FzfLua.files()
end, { desc = "Files" })
vim.keymap.set("n", "<leader>sr", function()
	FzfLua.resume()
end, { desc = "Resume fzf" })
-- Grep
vim.keymap.set("n", "<leader>/", function()
	FzfLua.live_grep()
end, { desc = "Grep (fzf)" })
vim.keymap.set("v", "<leader>/", function()
	FzfLua.grep_visual()
end, { desc = "Grep visual(fzf)" })
-- Git
vim.keymap.set("n", "<leader>gd", function()
	FzfLua.git_diff()
end, { desc = "diff" })
vim.keymap.set("n", "<leader>gb", function()
	FzfLua.git_blame()
end, { desc = "blame" })
vim.keymap.set("n", "<leader>gt", function()
	FzfLua.git_blame()
end, { desc = "tags" })
-- LSP
vim.keymap.set("n", "<leader>lr", function()
	FzfLua.lsp_references()
end, { desc = "references" })
vim.keymap.set("n", "<leader>lc", function()
	FzfLua.lsp_code_actions()
end, { desc = "code actions" })
vim.keymap.set("n", "<leader>ld", function()
	FzfLua.lsp_diagnostics()
end, { desc = "definitions" })
vim.keymap.set("n", "<leader>lD", function()
	FzfLua.lsp_diagnostics()
end, { desc = "definitions (workspace)" })
-- Neovim
vim.keymap.set("n", "<leader>uh", function()
	FzfLua.highlights()
end, { desc = "highlights" })
vim.keymap.set("n", "<leader>u?", function()
	FzfLua.helptags()
end, { desc = ":h tags" })
vim.keymap.set("n", "<leader>:", function()
	FzfLua.command_history()
end, { desc = "Command history" })
vim.keymap.set("n", "<leader>'", function()
	FzfLua.marks()
end, { desc = "Marks" })
vim.keymap.set("n", "<leader>j", function()
	FzfLua.jumps()
end, { desc = "Jumplist" })
vim.keymap.set("n", "<leader>\"", function()
	FzfLua.registers()
end, { desc = "Registers" })
vim.keymap.set("n", "<leader>.", function()
	FzfLua.undotree()
end, { desc = "Undo tree" })
