require("plugins.ui")
require("plugins.mini")
require("plugins.editing")
require("plugins.format")
require("plugins.folds")
require("plugins.markdown")
require("plugins.navigation")
require("plugins.colorscheme")
